version: '3.8'

services:
  catalog.api:
    container_name: lde.catalog.api
    build:
      context: .
      dockerfile: Catalog/Catalog.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
       - ConnectionString=server=www.alevelwebsite.com;port=5433;database=catalog;uid=postgres;password=postgres;
       - Authorization__Authority=http://www.alevelwebsite.com:5002
       - PathBase=http://www.alevelwebsite.com:5000
    depends_on:
      - postgres
    ports:
      - 5000:5000

  basket.api:
    container_name: lde.basket.api
    build:
      context: .
      dockerfile: Basket/Basket.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5005
       - Authorization__Authority=http://www.alevelwebsite.com:5002
       - PathBase=http://www.alevelwebsite.com:5005
       - Redis__Host=www.alevelwebsite.com:6380
       - Redis__CacheTimeout=00:30:10
    depends_on:
       - redis
    ports:
      - 5005:5005

  order.api:
    container_name: lde.order.api
    build:
      context: .
      dockerfile: Order/Order.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5006
       - ConnectionString=server=www.alevelwebsite.com;port=5434;database=order;uid=postgres;password=postgres;
       - Authorization__Authority=http://www.alevelwebsite.com:5002
       - PathBase=http://www.alevelwebsite.com:5006
    depends_on:
      - postgres
    ports:
      - 5006:5006

  web.mvc:
    container_name: lde.web.mvc
    build:
      context: .
      dockerfile: Web/MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - CatalogUrl=http://www.alevelwebsite.com:5000/api/v1/catalogbff
      - BasketUrlBff=http://www.alevelwebsite.com:5005/api/v1/basketbff 
      - BasketUrlApi=http://www.alevelwebsite.com:5005/api/v1/basketitem
      - OrderUrlApi=http://www.alevelwebsite.com:5006/api/v1/orderitem
      - Authorization__Authority=http://www.alevelwebsite.com:5002
      - IdentityUrl=http://www.alevelwebsite.com:5002
      - CallBackUrl=http://www.alevelwebsite.com/
      - RedirectUri=http://www.alevelwebsite.com/signin-oidc
    depends_on:
      - catalog.api
      - basket.api
      - order.api
      - identityserver
    ports:
      - 5001:5001
  identityserver:
    container_name: lde.identityserver
    build:
      context: .
      dockerfile: IdentityServer/IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - MvcUrl=http://www.alevelwebsite.com
      - CatalogApi=http://www.alevelwebsite.com:5000 
      - BasketApi=http://www.alevelwebsite.com:5005
      - OrderApi=http://www.alevelwebsite.com:5006 
    ports:
      - 5002:5002
  nginx:
    image: nginx
    container_name: lde.nginx
    ports:
      - 80:80
    volumes:
      - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ./Proxy/assets:/var/www/assets
  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8001:80 
  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
      - 5434:5432
  redis:
    image: redis
    container_name: lde.redis
    ports:
      - 6380:6379

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4